### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by lpcheng1208** [yezihack/go-mygen#7]
2020/08/17 14:41:27 core.go:113: 数据库连接成功
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.(*ModelS).findDbTables(0xc000080480, 0x16aad40, 0x0, 0x0, 0x0, 0x0)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/service.go:39 +0x4f0
main.(*ModelS).GetTableNameAndComment(0xc000080480, 0xc00001e1e0, 0x22)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/service.go:12 +0x8a
main.Commands(0x13cef93, 0x1)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:123 +0x2c5
main.start.func1(0xc0000c0160, 0x101010101, 0xc0000c0160)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:48 +0x252
github.com/urfave/cli.HandleAction(0x135cf40, 0x13e8530, 0xc0000c0160, 0xc000080240, 0x0)
	/Users/sgfoot/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc0000a3040, 0xc0000120b0, 0xb, 0xb, 0x0, 0x0)
	/Users/sgfoot/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
main.start()
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:55 +0xa5
main.main()
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/main.go:12 +0x86

mysql8.0版本出现这个错误

降级mysql5.7 正常使用

**Comment by lpcheng1208** [comment]
通过阅读源码发现问题是由于mysql8.0默认开启大小写敏感，导致获取到table_name,table_comment为nil 不能进行断言,通过修改model.Find 方法将field 转换为小写解决问题,PR已提！

**Comment by yezihack** [comment]
3.3.9版本.已经解决.
